// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:d503a826-7b1e-4c89-9eab-5fec8fcb9acb",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_jjAEWQExs",
    "aws_user_pools_web_client_id": "580ol1n8otktpbvn9qrtfl2blo",
    "oauth": {
        "domain": "fullrush0704d18b-0704d18b-dev.auth.us-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://localhost:8081/",
        "redirectSignOut": "https://localhost:8081/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS",
    "aws_user_files_s3_bucket": "fullrush9f99ca4bffb14612bd176ed454c58674-dev",
    "aws_user_files_s3_bucket_region": "us-west-2",
    "aws_dynamodb_all_tables_region": "us-west-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "dynamo1e44ee0b-dev",
            "region": "us-west-2"
        }
    ],
    "aws_content_delivery_bucket": "fullrush-20190417203916-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "http://fullrush-20190417203916-hostingbucket-dev.s3-website-us-west-2.amazonaws.com",
    "aws_appsync_graphqlEndpoint": "https://gek6xf7rsvb2nfqgywwlwujvbq.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "testetsetetstestmartinrest",
            "endpoint": "https://v0l2w2qg4k.execute-api.us-west-2.amazonaws.com/dev",
            "region": "us-west-2"
        }
    ]
};


export default awsmobile;
