# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
pod 'Firebase/Core', '~> 5.15.0'
target 'fullrush' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for fullrush

  target 'fullrush-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'fullrushTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'fullrush-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for fullrush-tvOS


end
